### ISSUE TITLE
请问，是怎么将H2数据库换成mysql数据库的？我根据spring cloud data flow文档配置，有些表同步下来了。但是访问页面的时候报错，说缺少了“uri_registry”表

### ISSUE THREAD

**Issue by cytgjf** [SamMACode/springcloud-dataflow#1]

**Comment by dongma** [comment]
我在本地通过docker-compose启动了cloud-dataflow服务，dataflow创建的数据表是没有问题的，包括了‘uri_registry’这张表。
我将docker-compose.yml文件上传到了issues-repair目录下，并使用相应的markdown文档进行说明，文档位置为: https://github.com/SamMACode/springcloud-dataflow/blob/master/issues-repair/config_dataflow_with_mariadb.md
